language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.0
    - android-23
    - extra-google-m2repository
    - extra-android-support

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t build-tools-23.0.0
  - echo y | android update sdk -u -a -t android-23
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository
  - echo y | android update sdk -u -a -t extra-android-support

jdk:
  - oraclejdk8

script:
  - ./gradlew build
